// OpenQASM 2.0 导出/导入：往返等价、Qiskit 风格源码解析、错误处理
#include <cmath>
#include <numbers>

#include <gtest/gtest.h>
#include <lqcs/lqcs.hpp>

using namespace lqcs;

namespace {

constexpr double kTol = 1e-12;

void expect_same_state(const QuantumCircuit& a, const QuantumCircuit& b) {
    StatevectorSimulator sim;
    const auto sa = sim.run_statevector(a);
    const auto sb = sim.run_statevector(b);
    ASSERT_EQ(sa.size(), sb.size());
    for (std::size_t i = 0; i < sa.size(); ++i) {
        EXPECT_NEAR(std::abs(sa[i] - sb[i]), 0.0, kTol) << "amplitude " << i;
    }
}

}  // namespace

TEST(Qasm, RoundTripPreservesState) {
    QuantumCircuit qc(3, 3);
    qc.h(0).x(1).sdg(2).rx(0.5, 0).u(0.3, 1.2, -0.7, 1).p(0.9, 2)
      .cx(0, 1).cz(1, 2).cp(1.1, 0, 2).crz(-0.4, 2, 0).swap(0, 2)
      .ccx(0, 1, 2).cswap(2, 0, 1).barrier().measure_all();

    const std::string qasm = io::to_qasm(qc);
    const QuantumCircuit parsed = io::from_qasm(qasm);

    EXPECT_EQ(parsed.num_qubits(), qc.num_qubits());
    EXPECT_EQ(parsed.num_clbits(), qc.num_clbits());
    EXPECT_EQ(parsed.num_instructions(), qc.num_instructions());
    expect_same_state(qc, parsed);
}

TEST(Qasm, ExportContainsExpectedHeader) {
    QuantumCircuit qc(1, 1);
    qc.h(0).measure(0, 0);
    const std::string qasm = io::to_qasm(qc);
    EXPECT_NE(qasm.find("OPENQASM 2.0;"), std::string::npos);
    EXPECT_NE(qasm.find("include \"qelib1.inc\";"), std::string::npos);
    EXPECT_NE(qasm.find("qreg q[1];"), std::string::npos);
    EXPECT_NE(qasm.find("creg c[1];"), std::string::npos);
    EXPECT_NE(qasm.find("h q[0];"), std::string::npos);
    EXPECT_NE(qasm.find("measure q[0] -> c[0];"), std::string::npos);
}

TEST(Qasm, ParsesQiskitStyleSource) {
    // Qiskit 常见导出风格：注释、pi 表达式、u2/u1、整寄存器测量
    const char* src = R"(
// generated by qiskit
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
u2(0,pi) q[0];        // = H
cx q[0],q[1];
u1(pi/4) q[1];        // = T
rz(3*pi/2) q[0];
barrier q[0],q[1];
measure q -> c;
)";
    const QuantumCircuit parsed = io::from_qasm(src);
    EXPECT_EQ(parsed.num_qubits(), 2u);

    QuantumCircuit expected(2, 2);
    expected.h(0).cx(0, 1).t(1).rz(3 * std::numbers::pi / 2, 0).barrier()
        .measure_all();
    expect_same_state(parsed, expected);
}

TEST(Qasm, MeasureMappingSurvivesRoundTrip) {
    QuantumCircuit qc(2, 2);
    qc.x(0).measure(0, 1).measure(1, 0);  // 交叉映射
    auto parsed = io::from_qasm(io::to_qasm(qc));
    auto c1 = StatevectorSimulator({.seed = 3}).run(qc, 50).counts();
    auto c2 = StatevectorSimulator({.seed = 3}).run(parsed, 50).counts();
    EXPECT_EQ(c1, c2);
}

TEST(Qasm, RejectsNonRepresentableGates) {
    {
        QuantumCircuit qc(2);
        qc.iswap(0, 1);
        EXPECT_THROW(io::to_qasm(qc), std::invalid_argument);
    }
    {
        QuantumCircuit qc(4);
        qc.mcx({0, 1, 2}, 3);  // 3 控制位超出 qelib1
        EXPECT_THROW(io::to_qasm(qc), std::invalid_argument);
    }
    {
        QuantumCircuit qc(2);
        const std::vector<std::size_t> cycle = {1, 2, 3, 0};
        qc.permutation(cycle, {0, 1});
        EXPECT_THROW(io::to_qasm(qc), std::invalid_argument);
    }
}

TEST(Qasm, RejectsMalformedSource) {
    EXPECT_THROW(io::from_qasm("OPENQASM 3.0;"), std::invalid_argument);
    EXPECT_THROW(io::from_qasm("OPENQASM 2.0; h q[0];"), std::invalid_argument);
    EXPECT_THROW(io::from_qasm("OPENQASM 2.0; qreg q[1]; frobnicate q[0];"),
                 std::invalid_argument);
}
